import hashlib
import pathlib
import sys
import tempfile
import unittest


sys.path.insert(0, str(pathlib.Path(__file__).parents[1] / "src"))
from autopa.gcode_context import (
    ContextTimeline,
    decode_context_marker,
    encode_context_marker,
    instrument_gcode,
    normalize_feature,
)


class GCodeContextTests(unittest.TestCase):
    def test_common_slicer_features_are_normalized(self):
        self.assertEqual(
            "external_perimeter", normalize_feature("External perimeter"))
        self.assertEqual(
            "external_perimeter", normalize_feature("WALL-OUTER"))
        self.assertEqual("infill", normalize_feature("Sparse infill"))
        self.assertEqual("solid_infill", normalize_feature("Top surface"))
        self.assertEqual("bridge", normalize_feature("Overhang perimeter"))
        self.assertEqual("support", normalize_feature("Support interface"))

    def test_marker_round_trip_is_compact_and_fail_closed(self):
        encoded = encode_context_marker({
            "layer": 12,
            "z_mm": 2.6,
            "feature": "External perimeter",
            "object": "würfel",
        })
        self.assertNotIn(" ", encoded)
        decoded = decode_context_marker(encoded)
        self.assertEqual(12, decoded["layer"])
        self.assertEqual(2.6, decoded["z_mm"])
        self.assertEqual("external_perimeter", decoded["feature"])
        self.assertEqual("würfel", decoded["object"])
        self.assertTrue(decoded["pa_eligible"])
        with self.assertRaises(ValueError):
            decode_context_marker("not-valid")

    def test_instrumentation_creates_copy_and_preserves_original(self):
        source_data = (
            b"; generated by PrusaSlicer\r\n"
            b";LAYER_CHANGE\r\n"
            b";Z:0.2\r\n"
            b";TYPE:External perimeter\r\n"
            b"G1 X10 Y10 E0.3 F1800\r\n"
            b";TYPE:Sparse infill\r\n"
            b"G1 X20 Y20 E0.7\r\n"
            b'EXCLUDE_OBJECT_START NAME="cube"\r\n'
            b"G1 X25 Y25 E0.9\r\n"
            b"EXCLUDE_OBJECT_END\r\n"
            b"G1 X30 Y30 E1.1\r\n"
        )
        with tempfile.TemporaryDirectory() as directory:
            source = pathlib.Path(directory, "input.gcode")
            output = pathlib.Path(directory, "input.autopa.gcode")
            source.write_bytes(source_data)
            source_hash = hashlib.sha256(source_data).hexdigest()
            manifest = instrument_gcode(source, output)
            self.assertEqual(source_data, source.read_bytes())
            self.assertEqual(source_hash, manifest["source_sha256"])
            self.assertFalse(manifest["original_modified"])
            self.assertEqual(4, manifest["marker_count"])
            self.assertEqual([0], manifest["layers"])
            self.assertIn("external_perimeter", manifest["features"])
            self.assertIn("infill", manifest["features"])
            self.assertEqual(["cube"], manifest["objects"])
            output_data = output.read_bytes()
            self.assertNotEqual(source_data, output_data)
            self.assertTrue(
                pathlib.Path(str(output) + ".context.json").is_file())
            marker_lines = [
                line.decode("ascii") for line in output_data.splitlines()
                if line.startswith(b"AUTOPA_MARK ")]
            self.assertEqual(4, len(marker_lines))
            contexts = [
                decode_context_marker(line.split(" VALUE=", 1)[1])
                for line in marker_lines]
            self.assertEqual(
                "external_perimeter", contexts[0]["feature"])
            self.assertEqual(5, contexts[0]["source_line"])
            self.assertEqual("infill", contexts[1]["feature"])
            self.assertEqual("cube", contexts[2]["object"])
            self.assertIsNone(contexts[3]["object"])

    def test_instrumentation_refuses_source_overwrite_and_reinstrumentation(self):
        with tempfile.TemporaryDirectory() as directory:
            source = pathlib.Path(directory, "input.gcode")
            output = pathlib.Path(directory, "output.gcode")
            source.write_text("G1 X1\n", encoding="utf-8")
            with self.assertRaises(ValueError):
                instrument_gcode(source, source)
            instrument_gcode(source, output)
            with self.assertRaises(ValueError):
                instrument_gcode(output, pathlib.Path(directory, "twice.gcode"))

    def test_timeline_uses_last_executed_not_future_marker(self):
        first = encode_context_marker({
            "layer": 3,
            "z_mm": 0.8,
            "feature": "External perimeter",
            "object": "cube",
        })
        future = encode_context_marker({
            "layer": 4,
            "z_mm": 1.0,
            "feature": "Support",
            "object": "cube",
        })
        timeline = ContextTimeline()
        timeline.observe([
            {
                "sequence": 2,
                "print_time": 20.0,
                "event": "context",
                "value": future,
            },
            {
                "sequence": 1,
                "print_time": 10.0,
                "event": "context",
                "value": first,
            },
        ])
        at_15 = timeline.resolve(15.0)
        self.assertEqual(3, at_15["layer"])
        self.assertTrue(at_15["pa_eligible"])
        at_20 = timeline.resolve(20.0)
        self.assertEqual(4, at_20["layer"])
        self.assertFalse(at_20["pa_eligible"])
        before = timeline.resolve(9.0)
        self.assertFalse(before["active"])


if __name__ == "__main__":
    unittest.main()
